# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Eduard Gubaidullin
title: CIO / IT Director
email: egubaidullin@gmail.com
website: cv.egub.win

# Dark Mode (true/false/never)
darkmode: false

# Social links

#twitter_username: facespics
#github_username:  sproogen

# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: eduard_gubaidullin
linkedin_username: egub
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: egub.win
  icon: fas fa-globe
  url: https://cv.egub.win
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-5SMXM7W"
# gtag: "UA-245371663-1"
# google_analytics: "UA-245371663-1"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Eduard. I'm a data-driven director of information technology with 10+ years experience in IT leadership positions. Design and implementation business strategies to maximize today's opportunities while preparing for the  future. Skilled in IT Service Management, IT Strategy, Digital Transformation, IT Infrastructure Management, Project Management, IOT. 

  I am most skilled in: <mark>IT-Management</mark>, <mark>Digitalization and Digital Transformation</mark> and <mark>IT Strategy</mark>

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: FINOTEC CO., LTD.
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Head Of Information Technology Department
        caption: November 2020 - Present
        quote: >
          Management of IT service in an international Company with branches in three countries of Southeast Asia and Europe.
        description: | # this will include new lines to allow paragraphs
          - Reformed an IT department to improve operational efficiency and guarantee 24/7/365 availability of critical services.
          - Created a culture of transparency, collaboration, accountability, and commitment to excellence, across the IT team.
          - Building infrastructure 'from scratch'.
          - Migration of all critical systems to the cloud.
          - Managed commercials, tenders, vendor selection and relationships.
          - Used solutions/technologies: Fortigate, Cisco, Symantec, VMware, Tableau, Microsoft, Synology, Bitrix24, Flyfonetalk, Line, Google workspace, Google Cloud, Alibaba Cloud, Docker/Kubernetes, Zabbix, Grafana, etc.
          - Over 1000 users.
      
      - layout: left
        title: NDA
        caption: 2016 - Present
        sub_title: Director of IT
        quote: >
          Business consulting.
        description: | # this will include new lines to allow paragraphs
          - Implemented Set Retail product from CSI Crystal for automation retail trade in conjunction with SaaS services ABM  Cloud(Automated ordering system)+ ABM Shelf (Shelf space optimisation)+ABM Loyality(Loyalty system) + Smart Mobile (software platform for developing corporate mobile solutions for mobile devices).
          - Digitization and optimization of business processes.
          - Integration of cloud services "Moy Sklad", "Business.Ru" with marketplaces and online stores on OpenCart platforms,  1C Bitrix, WordPress WooCommerce, Ecwid, CS.Cart.
          - Implemented IoT projects (ZigBee, Z-Wave, MQTT, BLE, LTE-M).
          - Implementation of dashboards and analytics with using SaaS;
          - Employee development, training, mentoring.
      - layout: left
        title: LLC Managing Company "Salute"
        caption: 2016 - 2018
        sub_title: Head of IT Department
        quote: >
          A large retail chain of stores.
        description: | # this will include new lines to allow paragraphs
          - Design and implementation of IT development strategy;
          - Optimizing and digitalizing business processes;
          - Budget planning and execution control;
          - Reducing IT operating costs (8%);
          - Implemented a system of training and testing of personnel. Improvement of the quality of personnel training;
          - Implementation of Business Intelligence solution
          - Implementation of internal and external electronic document management. Savings in paper costs and rental space for document storage;

      - layout: left
        title: OMC
        caption: 2015 - 2016
        sub_title: Head of IT Department
        quote: >
          Maintenance of the IT infrastructure of a distributed Arctic town (about 30 thousand people) during the construction of an LNG plant (the largest international project in Russia) of remote hard-to-reach facilities 24/7.
        description: | # this will include new lines to allow paragraphs
          - Budget planning.
          - Opening and technical support of shops and canteens (more than 30 units);
          - Support for software for accounting for accommodation and meals for employees, development of the required reports.
          - Organization of TV-retransmission;
          - Organization of wireless communication between remote and inaccessible objects using radio relay equipment.Maintenance of the IT infrastructure of a distributed Arctic town (about 30 thousand people) during the construction of an LNG plant (the largest international project in Russia) of remote hard-to-reach facilities 24/7. - Budget planning. - Opening and technical support of shops and canteens (more than 30 units); - Support for software for accounting for accommodation and meals for employees, development of the required reports. - Organization of TV-retransmission; - Organization of wireless communication between remote and inaccessible objects using radio relay equipment.

      - layout: left
        title: SPAR International
        caption: 2010 - 2015
        sub_title: Head of IT Department
        quote: >
          A regional retail chain of stores.
        description: | # this will include new lines to allow paragraphs
          - Development and implementation of an IT strategy at the enterprise (IT transformation as part of the Digital Transformation);
          - Controlled annual IT Infrastructure budget and provided optimization year on year through improvisation in technology.
          - Organization of a team of specialists, their motivation and professional growth (raised 4 leaders);
          - Digitalization of the Company's processes, implementation of a corporate business intelligence system;
          - Implementation of a warehouse management system (WMS). Reducing order assembly errors, speeding up order assembly, reducing inventory by up to 15%;
          - Reducing logistics costs - up to 11%. Distribution of loading of cars, taking into account the route of movement.
          - Optimised IT budget by reducing IT operating costs by 30%;
          - Ensuring the compliance of the trading and accounting system in accordance with the regulatory requirements of the legislation;
          - Implementation of the EDI system to optimize work with orders to suppliers;
          - Implementation of a loyalty system;
          - Development and implementation of our own auto-order system.
          - Automatic generation and printing of price tags.
          - Reducing financial losses, increasing the quality of customer service by creating a video surveillance department.
          
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Moscow Technical Institute
        caption: 2022
        sub_title: Project management

      - layout: left
        title: Yandex School of Data Analysis
        caption: 2022
        sub_title: Cloud Service Engineer
        
      - layout: left
        title: Sterlitamak State Pedagogical Institute
        caption: 2006
        sub_title: Technology and Entrepreneurship




  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
